### ISSUE TITLE
icon is not working

### ISSUE THREAD

**Issue by l02162010** [creativetimofficial/ct-vue-material-dashboard-pro#26]
I use font awesome
but it not working
<img width="663" alt="2018-10-20 12 22 35" src="https://user-images.githubusercontent.com/14830189/47251181-f493a380-d462-11e8-8ccf-b73d85d4f194.png">

**Comment by dragosct10** [comment]
Hi, @l02162010! Yes, it's not working because that string that you send from the sidebar it's wrapped into an `i` tag with some classes for material-icons so to fix this please go to `src/assets/components/SidebarPlugin/SidebarItem.vue` and inside this, please find this `<md-icon>{{link.icon}}</md-icon>` tag and replace with `<i>{{link.icon}}</i>`. 

Regards, 
Dragos
