### ISSUE TITLE
select in modal what happen ?

### ISSUE THREAD

**Issue by l02162010** [creativetimofficial/ct-vue-material-dashboard-pro#34]
<img width="560" alt="2018-11-02 2 35 33" src="https://user-images.githubusercontent.com/14830189/47897478-ea36c800-deac-11e8-8599-8a69f925f09e.png">
the select will over modal and under the modal.
please tell me how to fix it ?

**Comment by dragosct10** [comment]
Hi, @l02162010! Thank you for using our products. Please, tell us if you use the select in the modal or please be more specific. Regards, Dragos

**Comment by LaravDev** [comment]
As a workaround, try adding this CSS at the end of your component:

```
<style>
.md-menu-content.md-select-menu {
    z-index: 1200!important;
}
</style>
```

**Comment by l02162010** [comment]
@dragosct10 I use the select in the modal like this
<img width="802" alt="2018-11-03 1 08 26" src="https://user-images.githubusercontent.com/14830189/47948301-cb4a3b80-df69-11e8-9cb5-90ba3db69984.png">

**Comment by dragosct10** [comment]
Hi, @l02162010! This is weird because I just test it and in our side, the select is working fine. Please see this [video](https://www.dropbox.com/s/a5gq3sykf1yvfqx/vmdp.mov?dl=0) and for the code I used like this: 

![screenshot 2018-11-05 at 11 42 53](https://user-images.githubusercontent.com/17456857/47990485-4e959980-e0f0-11e8-9a0d-f88e96e657c7.png)

Did you make some changes in the scss? 

Regards,
Dragos

**Comment by sumitg-3767** [comment]
@dragosct10 
same issue, select does not work in modal, any stable fix?

**Comment by dragosct10** [comment]
Hi, @sumitg-3767! In our side, as you saw in my video that I posted everything it's working fine and I can't reproduce the bug, and from what I noticed here the z-index must be greater than 9998 so in this way will work. 

Regards, 
Dragos

**Comment by sumitg-3767** [comment]
.md-menu-content.md-select-menu {
    z-index: 9999;
}

would fix the issue
