### ISSUE TITLE
Wizard Form Validation

### ISSUE THREAD

**Issue by Danilmet** [creativetimofficial/ct-vue-material-dashboard-pro#8]
Hi,
In WizardForm, when I validating a Step, incorrect fields after pressing the "next" button after a couple of seconds starts look like valid.
p.s. It's from your Demo.

![image](https://user-images.githubusercontent.com/38282582/44085256-2043440e-9fe3-11e8-9df0-c22d28f46a66.png)
![2018-08-14](https://user-images.githubusercontent.com/38282582/44085328-5e550d22-9fe3-11e8-89cc-66ac1b15a5b9.png)
![image](https://user-images.githubusercontent.com/38282582/44085356-7549813e-9fe3-11e8-8946-ffc642eabf48.png)

**Comment by dragosct10** [comment]
Hi, @Danilmet! Thank you for using our products. It's weird what is happening because I made the same steps as you and nothing happened. We must do more tests to see what is the problem. Regards, Dragos

**Comment by zherman91** [comment]
I also am having issues with the validation of the Wizard. My first question is, in the 'FirstStep' file there is a section of code around line 65 as follows: 

`<md-field :class="[
          {'md-valid': !errors.has('email') && touched.email},
          {'md-form-group': true},
          {'md-error': errors.has('email')}]">
          <md-icon>email</md-icon>
          <label>Email</label>
          <md-input
            v-model="email"
            data-vv-name="email"
            type="text"
            name="email"
            required
            v-validate="modelValidations.email">
          </md-input>
          <slide-y-down-transition>
            <md-icon class="error" v-show="errors.has('email')">close</md-icon>
          </slide-y-down-transition>
          <slide-y-down-transition>
            <md-icon class="success" v-show="!errors.has('email') && touched.email">done</md-icon>
          </slide-y-down-transition>
        </md-field>`

My question to you is, where does 'errors' come from as I am getting an exception that 'errors' is not declared on the instance but reference during render? Also, I would also like to know how much of this relies on jQuery because i noticed on the template that its imported but seems like a bad practice to mix jQuery with Vue.js. Thoughts?

Let me know as soon as you can on how to proceed. I really appreciate the help. 

Thanks. 
Zac
